extends:
    - "@commitlint/config-conventional"
rules:
    type-empty:
        - 2
        - never
    scope-empty:
        - 2
        - never
    scope-enum:
        - 2
        - always
        -
            - release
            - travis-config
            - eslint-config
            - stylelint-config
            - webpack-config
            - babel-config
            - commitlint-config
            - jest-config
            - rollup-config
            - eslint-config
            - storybook-config
            - yarn-lock
            - readme
            - foobar
            - barbar
