language: node_js
node_js:
    - '10'
install:
    - npm ci
cache:
    directories:
        - "$HOME/.npm"
before_install:
    - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
script:
    - npm run lint:js
    - npm run lint:css
    - npm run test
    - commitlint-travis
deploy:
    skip_cleanup: true
    provider: script
    script: npm run lerna publish --yes
    email: vnys@statoil.com
    on:
        branch: master
        repo: batfink/react-storybook-setup
